# Site settings
title: NithinGunda
twitter_username: nithingsai
name: Gunda Venkata Nithin Sai

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/NithinGunda
 - title: LinkedIn
   url: 

#Any buzzword skills you want to include
skills:
 - Java 
 - SQL
 - JSP
 - HTML
 - Basic knowledge on BOOTSTRAP 3
 - CSS
 - JavaScript
 - JDBC

#Blogfeed is optional - including this will add JS to call the feed and populate blog list


#Work experience is required
roles:
 - title: Developed an IOT mini project
   start: 2017 july
   end: 2017 August
   Role: Developer
   description: A web application that controls all the lights and fans with an Android device.
   

 - title: Led display using IOT and .net
   start: 2017 September
   end: 2017 october
   Role: developer

   description: A device that displays the message sent by  android device.
   
 - title: Attendance moniter and accounting using Barcode Scanner
   start: 2018 january
   end: 2018 April
   Role: developer
   description: Through a unique barcode given to every student we scan and get the attendance details and fee details .

#Education is required
education:
 - level: Bachelor of Engineering (B.tech.)
   date: 2014-2018
   subject: Computer Science
   college: PVKK institute of technology.



#List of interesting Github repo/projects to include - optional
project:
 - github: https://nithingunda.github.io/

#Stackoverflow flair is optional
stackoverflow:

#Mobile apps section is optional
apps:


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong></strong> I have done my internship as a java trainee and developped a project which is an e-commerce type with use of jsp,servlets,html,css,jdbc and bootstrap. . <br/><br/>

